package com.demo;

/**
 * @author xue
 * @version 1.0.0
 * @ClassName data.java
 * @Description TODO
 * @createTime 2023年04月07日 14:08:00
 */
public class data {


    public static final String d1 = "Usage:\n"
            + "  traceroute [ -46dFITnreAUDV ] [ -f first_ttl ] [ -g gate,... ] [ -i device ] [ "
            + "-m max_ttl ] [ -N squeries ] [ -p port ] [ -t tos ] [ -l flow_label ] [ -w "
            + "waittime ] [ -q nqueries ] [ -s src_addr ] [ -z sendwait ] [ --fwmark=num ] host ["
            + " packetlen ]\n"
            + "Options:\n"
            + "  -4                          Use IPv4\n"
            + "  -6                          Use IPv6\n"
            + "  -d  --debug                 Enable socket level debugging\n"
            + "  -F  --dont-fragment         Do not fragment packets\n"
            + "  -f first_ttl  --first=first_ttl\n"
            + "                              Start from the first_ttl hop (instead from 1)\n"
            + "  -g gate,...  --gateway=gate,...\n"
            + "                              Route packets through the specified gateway\n"
            + "                              (maximum 8 for IPv4 and 127 for IPv6)\n"
            + "  -I  --icmp                  Use ICMP ECHO for tracerouting\n"
            + "  -T  --tcp                   Use TCP SYN for tracerouting (default port is 80)\n"
            + "  -i device  --interface=device\n"
            + "                              Specify a network interface to operate with\n"
            + "  -m max_ttl  --max-hops=max_ttl\n"
            + "                              Set the max number of hops (max TTL to be\n"
            + "                              reached). Default is 30\n"
            + "  -N squeries  --sim-queries=squeries\n"
            + "                              Set the number of probes to be tried\n"
            + "                              simultaneously (default is 16)\n"
            + "  -n                          Do not resolve IP addresses to their domain names\n"
            + "  -p port  --port=port        Set the destination port to use. It is either\n"
            + "                              initial udp port value for \"default\" method\n"
            + "                              (incremented by each probe, default is 33434), or\n"
            + "                              initial seq for \"icmp\" (incremented as well,\n"
            + "                              default from 1), or some constant destination\n"
            + "                              port for other methods (with default of 80 for\n"
            + "                              \"tcp\", 53 for \"udp\", etc.)\n"
            + "  -t tos  --tos=tos           Set the TOS (IPv4 type of service) or TC (IPv6\n"
            + "                              traffic class) value for outgoing packets\n"
            + "  -l flow_label  --flowlabel=flow_label\n"
            + "                              Use specified flow_label for IPv6 packets\n"
            + "  -w waittime  --wait=waittime\n"
            + "                              Set the number of seconds to wait for response to\n"
            + "                              a probe (default is 5.0). Non-integer (float\n"
            + "                              point) values allowed too\n"
            + "  -q nqueries  --queries=nqueries\n"
            + "                              Set the number of probes per each hop. Default is\n"
            + "                              3\n"
            + "  -r                          Bypass the normal routing and send directly to a\n"
            + "                              host on an attached network\n"
            + "  -s src_addr  --source=src_addr\n"
            + "                              Use source src_addr for outgoing packets\n"
            + "  -z sendwait  --sendwait=sendwait\n"
            + "                              Minimal time interval between probes (default 0).\n"
            + "                              If the value is more than 10, then it specifies a\n"
            + "                              number in milliseconds, else it is a number of\n"
            + "                              seconds (float point values allowed too)\n"
            + "  -e  --extensions            Show ICMP extensions (if present), including MPLS\n"
            + "  -A  --as-path-lookups       Perform AS path lookups in routing registries and\n"
            + "                              print results directly after the corresponding\n"
            + "                              addresses\n"
            + "  -M name  --module=name      Use specified module (either builtin or external)\n"
            + "                              for traceroute operations. Most methods have\n"
            + "                              their shortcuts (`-I' means `-M icmp' etc.)\n"
            + "  -O OPTS,...  --options=OPTS,...\n"
            + "                              Use module-specific option OPTS for the\n"
            + "                              traceroute module. Several OPTS allowed,\n"
            + "                              separated by comma. If OPTS is \"help\", print info\n"
            + "                              about available options\n"
            + "  --sport=num                 Use source port num for outgoing packets. Implies\n"
            + "                              `-N 1'\n"
            + "  --fwmark=num                Set firewall mark for outgoing packets\n"
            + "  -U  --udp                   Use UDP to particular port for tracerouting\n"
            + "                              (instead of increasing the port per each probe),\n"
            + "                              default port is 53\n"
            + "  -UL                         Use UDPLITE for tracerouting (default dest port\n"
            + "                              is 53)\n"
            + "  -D  --dccp                  Use DCCP Request for tracerouting (default port\n"
            + "                              is 33434)\n"
            + "  -P prot  --protocol=prot    Use raw packet of protocol prot for tracerouting\n"
            + "  --mtu                       Discover MTU along the path being traced. Implies\n"
            + "                              `-F -N 1'\n"
            + "  --back                      Guess the number of hops in the backward path and\n"
            + "                              print if it differs\n"
            + "  -V  --version               Print version info and exit\n"
            + "  --help                      Read this help and exit\n"
            + "\n"
            + "Arguments:\n"
            + "+     host          The host to traceroute to\n"
            + "      packetlen     The full packet length (default is the length of an IP\n"
            + "                    header plus 40). Can be ignored or increased to a minimal";

    public static void main(String[] args) {
        String str = "  hello world  ";
        String trimmed = str.trim();
        System.out.println("Original string: \"" + str + "\"");
        System.out.println("Trimmed string: \"" + trimmed + "\"");
    }


    public static final String d2 = "用法: find [-H] [-L] [-P] [-Olevel] [-D "
            + "help|tree|search|stat|rates|opt|exec] [path...] [expression]\n"
            + "\n"
            + "默认路径为当前目录；默认表达式为 -print\n"
            + "表达式可能由下列成份组成：操作符、选项、测试表达式以及动作：\n"
            + "\n"
            + "操作符 (优先级递减；未做任何指定时默认使用 -and):\n"
            + "      ( EXPR )   ! EXPR   -not EXPR   EXPR1 -a EXPR2   EXPR1 -and EXPR2\n"
            + "      EXPR1 -o EXPR2   EXPR1 -or EXPR2   EXPR1 , EXPR2\n"
            + "\n"
            + "positional options (always true): -daystart -follow -regextype\n"
            + "\n"
            + "normal options (always true, specified before other expressions):\n"
            + "      -depth --help -maxdepth LEVELS -mindepth LEVELS -mount -noleaf\n"
            + "      --version -xautofs -xdev -ignore_readdir_race -noignore_readdir_race\n"
            + "\n"
            + "比较测试 (N 可以是 +N 或 -N 或 N): -amin N -anewer FILE -atime N -cmin N\n"
            + "      -cnewer 文件 -ctime N -empty -false -fstype 类型 -gid N -group 名称\n"
            + "      -ilname 匹配模式 -iname 匹配模式 -inum N -ipath 匹配模式 -iregex 匹配模式\n"
            + "      -links N -lname 匹配模式 -mmin N -mtime N -name 匹配模式 -newer 文件\n"
            + "      -nouser -nogroup -path PATTERN -perm [-/]MODE -regex PATTERN\n"
            + "      -readable -writable -executable\n"
            + "      -wholename PATTERN -size N[bcwkMG] -true -type [bcdpflsD] -uid N\n"
            + "      -used N -user NAME -xtype [bcdpfls]\n"
            + "      -context 文本\n"
            + "\n"
            + "\n"
            + "操作: -delete -print0 -printf 格式 -fprintf 文件 格式 -print \n"
            + "      -fprint0 文件 -fprint 文件 -ls -fls 文件 -prune -quit\n"
            + "      -exec 命令 ; -exec 命令 {} + -ok 命令 ;\n"
            + "      -execdir 命令 ; -execdir 命令 {} + -okdir 命令 ;\n"
            + "\n"
            + "通过 findutils 错误报告页 http://savannah.gnu.org/ 报告错误及跟踪修定过程。如果您无法浏览网页，请发电子邮件至 "
            + "<bug-findutils@gnu.org>。";



    public static final String d3 = "********* simple selection *********  ********* selection by"
            + " list *********\n"
            + "-A all processes                      -C by command name\n"
            + "-N negate selection                   -G by real group ID (supports names)\n"
            + "-a all w/ tty except session leaders  -U by real user ID (supports names)\n"
            + "-d all except session leaders         -g by session OR by effective group name\n"
            + "-e all processes                      -p by process ID\n"
            + "                                      -q by process ID (unsorted & quick)\n"
            + "T  all processes on this terminal     -s processes in the sessions given\n"
            + "a  all w/ tty, including other users  -t by tty\n"
            + "g  OBSOLETE -- DO NOT USE             -u by effective user ID (supports names)\n"
            + "r  only running processes             U  processes for specified users\n"
            + "x  processes w/o controlling ttys     t  by tty\n"
            + "*********** output format **********  *********** long options ***********\n"
            + "-o,o user-defined  -f full            --Group --User --pid --cols --ppid\n"
            + "-j,j job control   s  signal          --group --user --sid --rows --info\n"
            + "-O,O preloaded -o  v  virtual memory  --cumulative --format --deselect\n"
            + "-l,l long          u  user-oriented   --sort --tty --forest --version\n"
            + "-F   extra full    X  registers       --heading --no-heading --context\n"
            + "                                      --quick-pid\n"
            + "                    ********* misc options *********\n"
            + "-V,V  show version      L  list format codes  f  ASCII art forest\n"
            + "-m,m,-L,-T,H  threads   S  children in sum    -y change -l format\n"
            + "-M,Z  security data     c  true command name  -c scheduling class\n"
            + "-w,w  wide output       n  numeric WCHAN,UID  -H process hierarchy\n";
}
